lib/karroake_web/router.ex
defmodule KarroakeWeb.Router do
  use KarroakeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug BasicAuth, use_config: {:karroake, :auth}
  end

  scope "/", KarroakeWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/sjung", RequestController, :new
    post "/sjung", RequestController, :create
    get "/spellista", RequestController, :index

    scope "/" do
      pipe_through :authenticated

      get "/song", SongController, :new
      post "/song", SongController, :create
      delete "/song", SongController, :delete
      delete "/request", RequestController, :delete
      get "/admin", AdminController, :index
      post "/admin", AdminController, :create
      delete "/admin", AdminController, :delete
      post "/admin/played", AdminController, :played
      post "/admin/unplayed", AdminController, :unplayed
    end
    
  end

  # Other scopes may use custom stacks.
  # scope "/api", KarroakeWeb do
  #   pipe_through :api
  # end
end

lib/karroake/karaoke_list/song.ex
defmodule Karroake.KaraokeList.Song do
  use Ecto.Schema
  import Ecto.Changeset

  alias Karroake.KaraokeList.Request

  @primary_key {:id, :integer, []}
  schema "songs" do
    field :artist, :string
    field :song, :string
    has_many :requests, Request

    timestamps(type: :utc_datetime)
  end

  @doc false
  def changeset(song, attrs) do
    song
    |> cast(attrs, [:id, :artist, :song])
    |> validate_required([:id, :artist, :song])
    |> unique_constraint(:id, name: :songs_pkey)
  end
end

lib/karroake_web/controllers/song_controller.ex
defmodule KarroakeWeb.SongController do
  use KarroakeWeb, :controller

  alias Karroake.KaraokeList
  alias Karroake.KaraokeList.Song

  def new(conn, _params) do
    changeset = KaraokeList.change_song(%Song{})
    songs = KaraokeList.list_songs()
    |> order_songs
    render(conn, "new.html", changeset: changeset, songs: songs)
  end

  def create(conn, %{"song" => request_params}) do
    case KaraokeList.create_song(request_params) do
      {:ok, _song} ->
        conn
        |> put_flash(:info, "Låten är tillagd")
        |> new(nil)
        
      {:error, %Ecto.Changeset{} = changeset} ->
        songs = KaraokeList.list_songs()
        |> order_songs
        conn
        # |> put_flash(:error, "Något gick fel")
        |> render("new.html", changeset: changeset, songs: songs)
    end
  end

  def delete(conn, %{"song" => id}) do
    song = KaraokeList.get_song!(id)
    {:ok, _song} = KaraokeList.delete_song(song)

    conn
    |> put_flash(:info, "Låten har tagits bort.")
    |> redirect(to: Routes.song_path(conn, :new))
  end

  defp order_songs(list), do: Enum.sort(list, fn song1, song2 -> song1.id > song2.id end)

end

lib/karroake_web/views/song_view.ex
defmodule KarroakeWeb.SongView do
  use KarroakeWeb, :view
end

lib/karroake_web/templates/song/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Något gick snett! :(</p>
    </div>
  <% end %>



    <div class="columns">
      <div class="col small">
  <%= label f, :id, "ID" %>
  <%= number_input f, :id %>
  <%= error_tag f, :id %>
      </div>
      <div class="col">
  <%= label f, :artist, "Artist" %>
  <%= text_input f, :artist %>
  <%= error_tag f, :artist %>
      </div>
    </div>
    <div class="columns">
      <div class="col">
  <%= label f, :song, "Låt" %>
  <%= text_input f, :song %>
  <%= error_tag f, :song %>
      </div>
    </div>
    <div class="horisontal-row">
  <%= submit "Lägg till" %>

  <%= link "Tillbaka", to: Routes.admin_path(@conn, :index), class: "button-link row-right" %>
    </div>
<% end %>

lib/karroake_web/templates/song/list.html.eex
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Artist</th>
      <th>Låt</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for song <- @songs do %>
    <tr>
      <td><%= song.id %></td>
      <td><%= song.artist %></td>
      <td><%= song.song %></td>
      <td><%= button "X", to: Routes.song_path(@conn, :delete, [song: song]), class: "warning thin", data: [confirm: "Är du säker på att du vill ta bort låten?"], method: :delete %>
    </tr>
<% end %>
  </tbody>
</table>

lib/karroake_web/templates/song/new.html.eex
<h1>Lägg till ny låt</h3>

<%= render "form.html", Map.put(assigns, :action, Routes.song_path(@conn, :create)) %>

<h1>Existerande låtar</h3>

<%= render "list.html", assigns %>